[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mode = "~Search"
mods = "Command|Shift"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.9

[window.padding]
x = 4
y = 4
