format = """
$username\
@\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$conda\
$python\
$character"""

add_newline = false
command_timeout = 1000

[cmd_duration]
format = '[$duration]($style) '
style = 'yellow'
min_time = 3000

[python]
format = '[$virtualenv]($style) '
style = 'bright-black'

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[$branch]($style) '
# format = '[$symbol$branch]($style) '

[character]
success_symbol = '[❯](green)'
error_symbol = '[✗](bold red)'
vicmd_symbol = '[V](bold blue)'

[username]
show_always = true
style_user = 'yellow bold'
style_root = 'black bold'
format = '\[[$user]($style)'
disabled = false

[hostname]
ssh_only = false
format =  '[$hostname](bold #d78787)\] '
disabled = false

[conda]
format = '\([$environment]($style)\) '

