#!/usr/bin/env sh

# ====================================================
# global settings
# ====================================================
# bsp, stack or float (default: bsp)
yabai -m config layout bsp

# Override default layout for space 2 only
# yabai -m config --space 2 layout float

# New window spawns to the left if vertical split, or top if horizontal split
# yabai -m config window_placement first_child

# New window spawns to the right if vertical split, or bottom if horizontal split (default)
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    2
yabai -m config bottom_padding 2
yabai -m config left_padding   2
yabai -m config right_padding  2
yabai -m config window_gap     2

# Override gaps for space 2 only
# yabai -m config --space 2 window_gap 0

# on or off (default: off)
yabai -m config auto_balance off

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# swap window when dropping a window on top of another
yabai -m mouse_drop_action swap

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse off

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus off


# ========================================================
# Application specific settings
# ========================================================
# float system preferences. Most of these just diable Yabai form resizing them. The followings are a few examples about how to set it.
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="^Software Update" manage=off
yabai -m rule --add label="About This Mac" app="^System Information" title="About This Mac" manage=off
yabai -m rule --add label="Raycast" app="^Raycast" manage=off
yabai -m rule --add label="Todoist" app="^Todoist" manage=off
# yabai -m rule --add label="Mail" app="Mail" manage=off
# yabai -m rule --add label="Calendar" app="^Calendar" manage=off
# yabai -m rule --add label="Friendly Streaming" app="^Friendly Streaming" manage=off

echo "yabai configuration loaded.."

#END
